<html>
    <head>
    <?php echo  $this->getChildHtml('head') ?>
    </head>
    <?php echo $this->getRequest()->getParams('id=123');?>
    <body>
        <div class ="header"><?php echo  $this->getChildHtml('header')?></div>
        <div class ="content">
        <?php echo  $this->getChildHtml('content') ?>
            <div class="left">left</div>
            <div class="middle">middle</div>
            <div class="right">right</div>
        </div>
        <div class ="footer"><?php echo  $this->getChildHtml('footer') ?></div>
        <h1>
            Hello
        </h1>
    </body>
</html>