<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Admin</title>
    
   <?php echo $this->getChildHtml('head'); ?>
</head>
<body>
   <?php echo $this->getChildHtml('header'); ?>
   <div class="Content">
      <?php echo $this->getChildHtml('content'); ?>
   </div>
   <div class="Footer"><?php echo $this->getChildHtml('footer'); ?></div>
</body>
</html>