<?php 
echo "<pre>";
$order=$this->getorder()->getData();?>
<table class="table table-striped">
        <tr>
            <td>Customer_id</td>
            <td>Order_id</td>
            <td>Order_Number</td>
            <td>Status</td>
            <td>PID(Quntity)</td>
            <td>Grand Total</td>
            <td>Accept</td>
            <td>Reject</td>
        </tr>
<?php
foreach ($order as $_order){
?>
            <tr>
            <td><?php echo $_order->getCustomerId()?></td>
            <td><?php echo $_order->getOrderId()?></td>
            <td><?php echo $_order->getOrderNumber()?></td>
            <td><?php echo $_order->getStatus()?></td>
            <?php $item=$this->getItem($_order->getOrderId());?>
            <td><?php foreach($item as $_item){
             echo $_item->getProductId()."(".$_item->getQty().")";
             }?> </td>
            <td> <?php echo $_order->getGrandTotal()?></td>
            <td><a href="<?php echo $this->getUrl("admin/order_orderview/acceptcancelation")."?id=".$_order->getOrderId()?>" ><button class="btn btn-success">Aceept</button></a></td>
            <td><a href="<?php echo $this->getUrl("admin/order_orderview/rejectcancelation")."?id=".$_order->getOrderId()?>" ><button class="btn btn-danger">Reject</button></a></td>
            </tr>
<?php }?>
</table>

