<?php
$customer=$this->customer();
// print_r($customer);
// die;
echo "<pre>";
// print_r($customers->getData());
?>
<table class="table table-striped table-dark ">
    <tr>
        <td>Customer_id</td>

        <td>Email</td>
    
        <td>First_Name</td>
    
        <td>Last_Name</td>
    
        <td>Billing_Address</td>
    
        <td>Billing_City</td>
    
        <td>Billing_Region</td>
   
        <td>Billing_Country</td>
   
        <td>Billing_Phone</td>
    
        <td>Shipping_Address</td>
    
        <td>Shipping_City</td>
   
        <td>Shipping_Region</td>
   
        <td>Shipping_Country</td>
    
        <td>Shipping_Phone</td>

        <td>Default</td>

        <td>Update</td>

    </tr> 
<tr>
    <td><?php echo $customer->getCustomerId();?></td>

    <td><?php echo $customer->getCustomerEmail();?></td>

    <td><?php echo $customer->getFirstName();?></td>

    <td><?php echo $customer->getLastName();?></td>

    <td><?php echo $customer->getBillingAddress();?></td>

    <td><?php echo $customer->getBillingCity();?></td>

    <td><?php echo $customer->getBillingRegion();?></td>

    <td><?php echo $customer->getBillingCountry();?></td>

    <td><?php echo $customer->getBillingPhone();?></td>

    <td><?php echo $customer->getShippingAddress();?></td>

    <td><?php echo $customer->getShippingCity();?></td>

    <td><?php echo $customer->getShippingRegion();?></td>

    <td><?php echo $customer->getShippingCountry();?></td>

    <td><?php echo $customer->getShippingPhone();?></td>

    <td><?php echo $customer->getDefault();?></td>

    <td><a href="<?php echo $this->getUrl("customer/account/register")."?id=".$customer->getCustomerId()?>"><button class="btn btn-outline-primary">Update</button></a></td>

</tr>
</table>