<?php $product=$this->getproductsdetail();
$corder=$this->getordersdetail();
$order=$this->getgrandtotal();
foreach ($product->getData() as $_product):?>
<p>
    <div><img src="<?php echo Mage::getImageUrl()."product/".$_product->getImageLink()?>" alt="" height="300" width="200"></div>
    <div>Price::<?php echo $_product->getPrice()?></div>
<?php endforeach;?>
<?php 
foreach($corder->getData() as $_corder):?>
    <div>Email:: <?php echo $_corder->getEmail(); ?></div>
<?php endforeach;?>
<?php
foreach($order->getData() as $_order):?>
    <div>Total:: <?php echo $_order->getGrandTotal(); ?></div>
<?php endforeach;?>
</p>