<form action="<?php echo $this->getUrl("sales/quote/savemethods") ?>"class="product" Method="post">
    <div class="container">
        <div class="boxes">
            <p>Shipping Method</p><br>
            <label for="smethod">Shipping Method</label>
            <select name="sdata[shipping_method]" id="smethod" value="" required>
                <option name="sdata[shipping_method]" value="Express">Express</option>
                <option name="sdata[shipping_method]" value="Normal">Normal</option>
            </select>
        </div>
        <div class="boxes" id="paymentMethod">
            <p>Payment Method</p><br>
            <input type="radio" name="pdata[payment_method]" id="upi" value="Upi" required />UPI <br>
            <input type="radio" name="pdata[payment_method]" id="debitcard" value="DebitCard" required />DebitCard <br>
            <input type="radio" name="pdata[payment_method]" id="creditcard" value="CreditCard" required />CreditCard <br>
            <div id="cnumber" >
            <label for="cnumber">Card Number</label>
            <input type="number" name="pdata[card_number]"  />
            </div>
           
        </div>
    </div>
    <input type="submit">
</form>

