<?php
$data=$this->getProduct();
// echo get_class($this);
// echo "<pre>";
// print_r($data);
?>
<form action="<?php echo $this->getUrl("admin/catalog_product/save")?>" method="post" class="product" enctype="multipart/form-data">
    <label hidden for="pid">Product_id</label>
    <input hidden type="text" id="pid" name="pdata[product_id]" value="<?php echo $data->getProductId()?>" />

    <label for="sku">sku</label>
    <input type="text" id="sku" name="pdata[sku]" value="<?php echo $data->getSku()?>" />

    <label for="productName">Product Name</label>
    <input type="text" id="productName" name="pdata[name]" value="<?php echo $data->getName()?>" />

    <label for="Color">Color</label>
    <input type="text" id="color" name="pdata[color]" value="<?php echo $data->getColor()?>" />

    <label for="size">size</label>
    <input type="text" id="size" name="pdata[size]" value="<?php echo $data->getSize()?>" />

    <label for="Description">Description</label>
    <textarea id="description" name="pdata[description]" cols="30" rows="10" value="<?php echo $data->getDescription()?>"></textarea>

    <label for="image link">image Link</label>
    <input type="file" name="pdata[image_link]" id="imageLink" value="<?php echo $data->getImageLink()?>">

    <label for="link">Link</label>
    <input type="file" name="pdata[link]" id="link" value="<?php echo $data->getLink()?>">

    <label for="category">Category</label>
    <select name="pdata[category_id]" id="category_id">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
    </select>

    <label for="price">Price</label>
    <input type="text" id="price" name="pdata[price]" value="<?php echo $data->getPrice()?>" />

    <label for="manufacturerCost">Manufacturer Cost</label>
    <input type="text" id="manufacturerCost" name="pdata[mfr_cost]" value="<?php echo $data->getMfrCost()?>" />

    <label for="shippingCost">Shipping Cost</label>
    <input type="text" id="shippingCost" name="pdata[shipping_cost]" value="<?php echo $data->getShippingCost()?>" />

    <label for="totalCost">Total Cost</label>
    <input type="text" id="totalCost" name="pdata[total_cost]" value="<?php echo $data->getTotalCost()?>" />

    <label for="margin percentage">Margin Percentage</label>
    <input type="text" id="marginPercentage" name="pdata[margin_percentage]" value="<?php echo $data->getMarginPercent()?>" />

    <label for="min price">Min Price</label>
    <input type="text" id="minPrice" name="pdata[min_price]" value="<?php echo $data->getMinPrice()?>" />

    <label for="status">Status</label>
    <select name="pdata[status]" id="status">
        <option value="1">enable</option>
        <option value="0">disable</option>
    </select>

    <input type="submit" name="" value="submit" />
</form>