<pre>
<?php
$productCollection = Mage::getModel('catalog/product')->getCollection()
->addFieldToFilter('name',['eq'=>'jk'])
->addFieldToFilter('groupby','name')
->addFieldToFilter('orderbydsc','name');
    // ->addFieldToFilter('name',['eq'=>'jk'])
    // ->addFieldToFilter('name',['like' => 'bet'])
    // ->addFieldToFilter('name',['gt' => 'bet'])
    // ->addFieldToFilter('name',['in' => 'bet'])
    // ->addFieldToFilter('name',['between' => 'bet'])
    // ->addFieldToFilter('name',['orderby'=> 'name'])
    ;
    // print_r($productCollection);
// foreach($productCollection->getData() as $product) {
//     print_r($product->getStatus());
//     // print_r($product);
// }
// // echo get_class($productCollection); 
// ?>
<table class="table table-striped table-dark">
    <tr>
        <td>
            product_id
        </td>
        <td>
            sku
        </td>
        <td>
            name 
        </td>
        <td>
            color
        </td>
        <td>
            size
        </td>
        <td>
            description
        </td>
        <td>
            image
        </td>
        <td>
            link
        </td>
        <td>
            category_id
        </td>
        <td>
            price
        </td>
        <td>
            mfr_cost
        </td>
        <td>
            shipping_cost
        </td>
        <td>
            total_cost
        </td>
        <td>
            margin_percent
        </td>
        <td>
            min_price
        </td>
        <td>
            status
        </td>
        <td>update</td>
        <td>delete</td>
    </tr>
    <?php 
    foreach($productCollection->getData() as $data) {
        // print_r($data);
        ?>
    <tr>
        <td><?php echo $data->getProductId()?></td>
        <td><?php echo $data->getSku()?></td>
        <td><?php echo $data->getName()?></td>
        <td><?php echo $data->getColor()?></td>
        <td><?php echo $data->getSize()?></td>
        <td><?php echo $data->getDescription()?></td>
        <td><?php echo $data->getImageLink()?></td>
        <td><?php echo $data->getLink()?></td>
        <td><?php echo $data->getCategoryId()?></td>
        <td><?php echo $data->getPrice()?></td>
        <td><?php echo $data->getMfrCost()?></td>
        <td><?php echo $data->getShippingCost()?></td>
        <td><?php echo $data->getTotalCost()?></td>
        <td><?php echo $data->getMarginPercentage()?></td>
        <td><?php echo $data->getMinPrice()?></td>
        <td><?php echo $data->getStatus()?></td>
        <td><a href="<?php echo $this->getUrl("admin/catalog_product/form")."?id=".$data->getId()?>"><button class="btn btn-primary">Update</button></a></td>
        <td><a href="<?php echo $this->getUrl("admin/catalog_product/delete")."?id=".$data->getId()?>"><button class="btn btn-danger">Dalete</button></a></td>
    </tr> 
    <?php } ?> 
</table>
