<?php
$product = Mage::getModel('catalog/product')->getCollection()
// ->addFieldToFilter('name',['eq'=>'jk'])
// ->addFieldToFilter('groupby','name')
// ->addFieldToFilter('orderbydsc','name');
    // ->addFieldToFilter('name',['eq'=>'jk'])
    // ->addFieldToFilter('name',['like' => 'bet'])
    // ->addFieldToFilter('name',['gt' => 'bet'])
    // ->addFieldToFilter('name',['in' => 'bet'])
    // ->addFieldToFilter('name',['between' => 'bet'])
    // ->addFieldToFilter('name',['orderby'=> 'name'])
    ;
    //  print_r($product->getData());
// foreach($productCollection->getData() as $product) {
//     print_r($product->getStatus());
//     // print_r($product);
// }
?>
<table class="table table-striped table-dark">
    <tr>
        <td>
            product_id
        </td>
        <td>
            sku
        </td>
        <td>
            name 
        </td>
        <td>
            color
        </td>
        <td>
            size
        </td>
        <td>
            description
        </td>
        <td>
            image
        </td>
        <td>
            link
        </td>
        <td>
            category_id
        </td>
        <td>
            price
        </td>
        <td>
            mfr_cost
        </td>
        <td>
            shipping_cost
        </td>
        <td>
            total_cost
        </td>
        <td>
            margin_percent
        </td>
        <td>
            min_price
        </td>
        <td>
            Items In Inventory
        </td>
        <td>
            status
        </td>
        <td>update</td>
        <td>delete</td>
    </tr>
    <?php foreach($product->getData() as $product) : ?>
    <tr>
        <td><?php echo $product->getProductId()?></td>
        <td><?php echo $product->getSku()?></td>
        <td><?php echo $product->getName()?></td>
        <td><?php echo $product->getColor()?></td>
        <td><?php echo $product->getSize()?></td>
        <td><?php echo $product->getDescription()?></td>
        <td><img src='<?php echo Mage::getImageUrl()."product/".$product->getImageLink() ?>' class="d-block w-100" alt="" height="100" width="100"></td>
        <td><?php echo $product->getLink()?></td>
        <td><?php echo $product->getCategoryId()?></td>
        <td><?php echo $product->getPrice()?></td>
        <td><?php echo $product->getMfrCost()?></td>
        <td><?php echo $product->getShippingCost()?></td>
        <td><?php echo $product->getTotalCost()?></td>
        <td><?php echo $product->getMarginPercentage()?></td>
        <td><?php echo $product->getMinPrice()?></td>
        <td><?php echo $product->getInventory()?></td>
        <td><?php echo $product->getStatus()?></td>
        <td><a href="<?php echo $this->getUrl("admin/catalog_product/form")."?id=".$product->getId()?>"><button class="btn btn-primary">Update</button></a></td>
        <td><a href="<?php echo $this->getUrl("admin/catalog_product/delete")."?id=".$product->getId()?>"><button class="btn btn-danger">Dalete</button></a></td>
    </tr> 
    <?php endforeach; ?> 
</table>
