<?php //$category=Mage::getModel("catalog/category")->getCollection();
// print_r($category);
$product=$this->getProduct();
if(!$product->getData()){
    echo "That category product doesn't exist in our list";
}
else{
?>
<table class="table table-stripped table-dark">
<tr>
        <td>
            image
        </td>
        <td>
            product_id
        </td>
<?php foreach ($product->getData() as $_product) {
?>
     <tr>
        <td><img src='<?php echo Mage::getImageUrl()."product/".$_product->getImageLink() ?>' class="d-block w-100" alt="" height="100" width="100"></td>
        <td>
        <form action=" <?php echo $this->getUrl("sales/quote/add")?>" method="post">
        <input hidden type="text" name="qdata[product_id]" value="<?php echo $_product->getProductId()?>">
        <label for="qty">Quntity</label>
        <input type="number" name="qdata[qty]" id="qty" max="<?php //echo $inventory=$_product->getInventory()*(0.5)?>"/>    
        <button type="submit" class="btn btn-outline-primary">AddCart</button>
        </form>
    </td>
     </tr>
<?php }?>
</table>
<?php } ?>
