<div>
    <div>
    <a href="<?php echo $this->getUrl("admin/catalog_product/list")?>"><button class="btn btn-success">Products</button></a>
    </div>
    <div>
    <a href="<?php echo $this->getUrl("admin/catalog_product/form")?>"><button class="btn btn-success">AddProduct</button></a>
    </div>
    <div>
    <a href="<?php echo $this->getUrl("admin/catalog_category/view")?>"><button class="btn btn-success">Category</button></a>
    </div>
</div>