<header class="p-3 bg-secondary text-white mb-5">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <!-- <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"> -->
                    <img src="\phppractice\mvc\skin\images\icons\logo.png" height="40" width="40" />
                    <use xlink:href="#bootstrap" />
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="<?php echo $this->getUrl("page/index")?>" class="nav-link px-2 text-white">Home</a></li>
                <li><a href="<?php echo $this->getUrl("admin/order_orderview/orderview") ?>" class="nav-link px-2 text-white">View Orders</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
                <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
                <li><a href="#" class="nav-link px-2 text-white">About</a></li>
            </ul>

            <!-- <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
            </form> -->

            <div class="text-end">
                <a href="<?php echo $this->getUrl("admin/catalog_product/list")?>"><button type="button" class="btn btn-outline-light me-2">Login</button></a>
                <a href="<?php echo $this->getUrl("admin/account/logout")?>"><button type="button" class="btn btn-warning">logout</button></a>
            </div>
        </div>
    </div>
</header>