<footer class="bg-dark text-white py-4 mt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <h5>About Us</h5>
                Tech Company With Over 200+ Employee Strength</p>
            </div>
            <div class="col-md-3 col-sm-6">
                <h5>Quick Links</h5>
                <ul class="">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Shop</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6">
                <h5>Navigation</h5>
                <ul class="">
                    <li><a href="<?php echo $this->getUrl("admin/catalog_product/list")?>">Products</a></li>
                    <li><a href="#">Clothes</a></li>
                    <li><a href="#">Electronics</a></li>
                    <li><a href="#">Shoes</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6">
                <h4>&copy;All Right Reserved</h4>
                <h5>Contact Us</h5>
                <address>
                    B-305,the First<br>
                    CybercomeCreation,Keshvbaug<br>
                    <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>
            </div>
        </div>
    </div>
</footer>