<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Header</title>
    <style>
        /* a{
            color: aliceblue;
        }
        a:hover{
            color: aqua;
        }
        .button {
            background-color: aliceblue;
            border: none;
            color: white;
            padding: 20px;
            text-align: center;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
        }
        .button{
            border-radius: 12px;
        }
        .button a{
            text-decoration: none;
            text-decoration-color: whitesmoke;
        }
        .button:hover{
            background-color: black;
            border: none;
            color: aqua;
            padding: 20px;
            text-align: center;
            text-decoration-color: red;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
        } */
    </style>
</head>
<body>
    <div>
        <nav>
            <button class="button button"><a href="Register.phtml">Register</a> </button>
            <button class="button button"><a href="login.phtml">login</a></button>
            <button class="button button"><a href="Category.phtml">Category</a></button>
            <button class="button button"><a href="Product.phtml">Product</a></button>
            <button class="button button"><a href="Cart.phtml">Cart</a></button>
            <button class="button button"><a href="logout.phtml">logout</a></button>
        </nav>
    </div>
    
</body>
</html>