<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<?php $js=$this->getJs();
      $css=$this->getCss();
?>
<?php if (count($js)):?>
<?php foreach ($js as $_js):?>
<script src="<?php echo Mage::getBaseUrl().$_js ?>"></script>
<?php endforeach; ?> 
<?php endif;?>

<?php if(count($css)):?>
<?php foreach ($css as $_css):?>
    <link rel="stylesheet" href="<?php echo Mage::getBaseUrl().$_css ?>"></link>
<?php endforeach;?>
<?php endif;?>





