<form action="<?php echo $this->getUrl("license/license/add")?>" method="post">
<label for="uname">User_name</label>
<input type="text" name="cdata[user_name]" id="uname" value="<?php echo Mage::getSingleton('core/session')->get('user_name') ?>">
<?php 
$data=$this->getLicenceRate();?>
<select name="cdata[state]" id="">
<?php foreach($data->getData() as $_data):?>
    <option name="cdata[state]"><?php echo $_data->getState()?></option>
<?php endforeach;?> 
</select>
<br>
<label for="type">Type</label>
<br>
<?php $ltype=[];
foreach($data->getData() as $_data):?>
<?php $type=$_data->getLicenceType();
$ltype[]=$type;?>
<?php endforeach;
for($i=0;$i<(count(array_unique($ltype)));$i++):?>
<input type="checkbox" id="type" name="cdata[licence_type][<?php print_r($ltype[$i])?>]" value="<?php print_r(($ltype[$i]))?>"><?php print_r(($ltype[$i]))?> <br>
<?php endfor;?>
<input type="submit" name="submit">
</form>