<!-- <?php //$banner=Mage::getModel("banner/banner")->getCollection();?>
 <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
  <div class="carousel-item active">
      <img src='<?php //echo Mage::getImageUrl()."banner/"."p1mad1.jpg" ?>' class="d-block w-100" alt="..." height="500" width="300">
    </div>
  <?php //foreach ($banner->getData() as $bannerItem): ?>
    <div class="carousel-item">
      <img src='<?php //echo Mage::getImageUrl()."banner/".$bannerItem->getName() ?>' class="d-block w-100" alt="" height="500" width="300">
    </div>
  </div>
  <?php //endforeach; ?>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>  -->

<?php
$bannerModel = Mage::getModel("banner/banner")->getCollection();
?>

<div id="carouselExampleCaptions" class="carousel slide carousel-fade carousel-dark mt-2 mb-2" data-bs-ride="carousel"
    style="width:80%;margin:auto">
    <div class="carousel-inner">
        <?php $count = 0;
        foreach ($bannerModel->getData() as $banner){?>
            <div class="carousel-item<?php if ($count == 0)
                echo ' active'; ?>" data-bs-interval="4000">
                <img src="<?php echo Mage::getImageUrl() . 'banner/' . $banner->getImage() ?>"
                    class="d-block w-100 h-75" alt="..." height="300" width="300">
                <div class="carousel-caption d-none d-md-block">
                    <h5 class=><?php echo $banner->getTitle(); ?></h5>
                </div>
            </div>
            
        <?php $count++;} ?>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>