<form action="<?php echo $this->getUrl("customer/address/save")?>" class="product" method="post">
            <label for="address">Address</label>
            <input type="text" id="address" name="add[address]"/>
            <label for="city">City</label>
            <input type="text" id="city" name="add[city]"/>
            <label for="region">Region</label>
            <input type="text" id="region" name="add[region]"/>
            <label for="country">Country</label>
            <input type="text" id="country" name="add[country]"/>
            <label for="phone">Phone</label>
            <input type="text" id="phone" name="add[phone_no]"/>
            <label for="zip">Zip_Code</label>
            <input type="text" id="zip" name="add[zip_code]"/>
            <input type="submit">
</form></